name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main  # falls dein Branch anders heißt, z. B. "master", anpassen

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.149.0'  # deine Hugo-Version einsetzen (kannst mit "hugo version" prüfen)
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
